services:
  client:
    build:
      context: ./client
      args:
        - VITE_LEX_BOT_ALIAS_ID
        - VITE_LEX_BOT_ID
        - VITE_AWS_REGION
        - VITE_AWS_IDENTITY_POOL_ID
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - ml

  ml:
    build: ./ml-api
    ports:
      - "5000:5000"
    env_file:
      - ./ml-api/.env
